sudo: required
dist: trusty
language: node_js
node_js:
- node
cache: ccache

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgcc-4.8-dev
    - libstdc++-4.8-dev
    - libobjc-4.8-dev
    - libjsoncpp0
    - libobjc-4.8-dev
    - libstdc++6
    - checkinstall
  sauce_connect:
    username:
      secure: awXNvlwMXZ0t419TKnB2Gfbg2CjU0fSmuCNq+rklGV3vQQPPweQjW7W4mdaMGr4UMzNlwlG+PKEabhwV/PmzZXhBfe1H9bJKO4TmsEONTO2i5WrYAHHXEpAwCpF3SUf1hecL0uS5dFel0mvJHrZwTdupLzFmEOLmt1N+b9z3DqfiP//Uc1aqnThsaflpz8MG4evVbUNPM/AiNlLTQTqZuIsmaoHGR7lqgwZSZWhB3x6ut5A7zEActWiFu4iSVdWA7l7pJInhvx8pEoL3vV2ZRIKLF0HexMk0Ykm+n5jO5BTpGm0GsxseBk6zK+AEeS4yAucj8DFr0QtiSgLaOwBwvrRMlF4ryzjzxmnC7x5wIpRSpyHP9XQQX+1q5LPAKNR/aYSjrWKJJhr00R7xQ2BQg7xMHYajcK4ILiX8kXXQZQ3aKXqDs6rpgUJqci2JMdfhziIlT1lnR7y5B3CLjWs70ZSvm+UP8cm/ZRfSrMm1NH2ENUnInRry938dIQq1lHgnk7JYjYuJy8VlG5tCmi2tac8LJCDd+/62Io2r5YTp5kc/+qMAuLonGit5mZYF4YaAJI1mWOjfAaIHyGnY+5O7t/mBJalngnE2q6QgcN6Dmdd7khO2AmNGCG44DpwTKSV69XyxbExrnSfmaibtYVmpfRt2XvDrF9fp2/FT239nUcw=
    access_key:
      secure: UiJJRJPRm5pH8quE2EvCooGkykll1MwadYMakTDPJIH3Ecn+fKOgntrovReJlwuH74Mi2sxS+7j8zrdOhd1fiOyY8zDgvAUEviWa2Q5UW82EdQ0ReVUtR6t63rSgFqhH20gsH1zPh96vIfmWRY52WACX3yBgmrMuZGjMStXzjXeBH2G5weWhYanbE6jRX/AWVuK25/etrzFWfXFYlXgZNptn9XBBsirxAv0QFjt0uBS4c3ANUd+MtKohlKdYdmUIPY/6uoWjZk3i7COmlWXKNsDsT+IuxTTx8DyMqUf1/9dn8/KobKBWlRWxM9Kzawn49ydJrkgSoAnYjTdUh5XCwq/sW/TWS7kWWZCBcJa9xL4M3e+6m2UDmgeX9jGZuD/OGE/5CSbL0Mv5YKGSY5Ek/rT+HCBGv/fXSXNLfSyX+KhS6/6ZchVj+KduEgTmKBuZ3x6N1pBfBT7HbgNBX3Opgxbs2iomXRcTDsrxEirLWrec5CsJ3pf/hhkBcjz1sBwze7ShYqbemEdNcVjtQtdhH+4Hm+JEuJILJoWajLMWTUL7tInokCc3F03w17bZIbafm+PjcUV30g+kE1F6axLt4GPBZVBBuuKOOyAWy1R47RCr4Teh5pLB+9byX5pXSZ0mUAirR2R5qwENh6cWmR2s/FU5QswGR0nGjX4Kohq84Lc=
  code_climate:
    repo_token:
      secure: i26rPVMhJbffCwkWfItH7fsmEK2bxjcxSj/+ktRK+RF7oaPJVzJzJHkEuJ7/WVz4tQJeul/+pSiInpyj6UkdOz1QMWHQ/liSIP3KlnUJ4JMqBn2jrFCgrVN3wPqwoa9zXuHsHoO/uLZzX2kqsPCwwypWLV95NgINUGUX6RLdnrxh+lrFmWsDwfmMeTfqobOXCSwCu1tX7MqHYHZhzakrunVGxlpiMUlHHPxb+4ap8cYv6JGWhxITQRJI/G/O1WprxgQu+j1xp6odXhZBkL0jeZHwOExj3YB56LTxDE3rZVhsMhMAawsHMJzr9CYNe5eR/zjlRD+uwS5649L0iFiHM0JpBK4igYi439zTqIfdQJlQnIxFUJ9yfOp41KbFF0tMGdpCDQc1brkxpuADQjrrFnlKnmXE13Y8iGnxKg0G1BxvyuviqmsHwVqVGosaoMbbEWy4X+sy7EGEf29PaDuPnoqCjZcZ/j3vVoyv8FJNTJfcwJAE68WT+tU5PZY4mBE3YIZqI/Zq39ndrLlooJ/8mF64119rpRVF6da4nXXgbo1nGn+S8Gv/+Tiu9XofrCQgsGTBhw5R1TpA6OCoNLVMYhVG6aW5Jyzxy/SoOVCfgxCfws94sNJi85R24RlnpY8Tki4D77JfRGmi0Fl1mWlEkTZ39ESsoCdSesnIuKSAJpA=

env:
  global:
    secure: a7Q9g1y8U6Z3Tx9z3Lm1IQAfPG8Xn7o5XUAUewwGvB6qHw6DpcRxY2xkBpMV1uYJQpqojLNWPIXUWGWG+VkedzwgJZGDFx/87YII/h/wufLY5ZTjLnQXV12PMgzxT/1ubLdKd+xP+JzxzG1dLSAzfeDTc49lzeTQapu6y+SV+4Di64emyiJejGqSfJf/2ZWm1Zy50QgX3xHIBb+7NMiD3sdjVx6rlTJ288Y6McPG357YQimbGpd1VjkrsqNkiR7lrdNi+kKn9FVghm3B3gG88y00wcFdCfZsbkiQ9VeNw43pjwSON8AFC6YUTGzovJGGn6FQIXKPBMQiQzRXCbavcf90oFFQzPJ1EpBHQNWqJkPjOdBJfB5XdSLDxGpwTEC0PU9IoMgfjHq1LCrTKqdxijK+lIaMf12vaG2ypR7MJTcoHJvRHInDPamRLPDge5DfOWn9ZQYCfJCAjN/ld9kquz8im9eLNeZA9CEr1YIkCVUV5O1okMT9A0YyKOoLNedkB8yVXqjJrBUz41N+Tv9HR6dH55C2au+jUYWqtDVWd9DuGJpFangnrOIwv/vDZFI8yr03yEhH7Z+OpVc003UFA52PRyq+stQ1UCPohuhzQxVWFSjtJTkc6MsrAb+cFodTwyEbD7DzAzKKZKfP6BpxYUTSD2vpqlfdWOKZ835kT0I= # NPM_TOKEN

before_install:
- wget http://famreiser.ch/llvm/cmake-3.8.1.tar.gz && tar -xzf cmake-3.8.1.tar.gz && sudo dpkg -i cmake_3.8.1-1_amd64.deb
- wget http://famreiser.ch/llvm/llvm-5.0-20170527.tar.gz
- mkdir llvm && tar -xzf llvm-5.0-20170527.tar.gz -C llvm
- export CC="ccache $(pwd)/llvm/bin/clang"
- export CXX="ccache $(pwd)/llvm/bin/clang++"

install:
- npm config set LLVM_CONFIG $(pwd)/llvm/bin/llvm-config
- npm install
- npm run bootstrap

after_success:
- npm run coverage
- ./deploy.sh
after_failure:
- cat npm-debug.log || true
- cat packages/compiler/npm-debug.log || true
- cat packages/runtime/npm-debug.log || true
- cat packages/benchmark/npm-debug.log || true
- cat lerna-debug.log || true